//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int AcctID { get; set; }
        public string type { get; set; }
        public int BankID { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
