//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanID { get; set; }
        public string Name { get; set; }
        public int BankID { get; set; }
        public string Company { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Payee Payee { get; set; }
    }
}
