//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public Payee()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public string Name { get; set; }
        public decimal LastAmount { get; set; }
        public string Category { get; set; }
        public string Note { get; set; }
        public string To { get; set; }
    
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
