//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransID { get; set; }
        public int AcctID { get; set; }
        public string To { get; set; }
        public int CategoryID { get; set; }
        public string Note { get; set; }
        public bool Reconciled { get; set; }
        public int CheckNum { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransDate { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
    }
}
